apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: circleci-demo-eks-argocd-app
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: circleci-demo-eks-argocd-app
              servicePort: http
