apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: circleci-demo-eks-argocd-app
  newName: 660990364978.dkr.ecr.ap-northeast-1.amazonaws.com/tadashi-eks-argocd-demo
  newTag: 8b7fa6736118395b0318669e834a8a29527f4cd7
