apiVersion: v1
kind: Service
metadata:
  name: circleci-demo-eks-argocd-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: circleci-demo-eks-argocd-app
  type: LoadBalancer
